FROM anderspitman/tidepool-common:latest
MAINTAINER Anders Pitman <tapitman11@gmail.com>

COPY shoreline.tar.gz shoreline.tar.gz
COPY launch_container launch_container

ENTRYPOINT ["sh", "launch_container"]
